# Generated by Django 3.2.6 on 2021-08-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.CharField(default='some', max_length=100),
        ),
    ]
