# Generated by Django 3.2.6 on 2021-08-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_topic_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='learning',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='life',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='working',
        ),
    ]
