# Generated by Django 3.2.6 on 2021-08-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210817_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='idea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='learn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='life',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='work',
            field=models.BooleanField(default=False),
        ),
    ]
